
apiVersion: v1
kind: Service
metadata:  
  name: docker-registry
  namespace: docker-registry-proxy-cache
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
    release: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008